'use client';

import Image from 'next/image';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { CmsDocument, ContentEntry, ContentType, MediaItem } from '@/lib/cms/types';
import type { Product } from '@/lib/data';

type Tab = 'overview' | 'content' | 'products' | 'media' | 'forms' | 'audit';
const nav: { id: Tab; label: string; icon: string }[] = [{ id:'overview',label:'Visão geral',icon:'⌂'},{id:'content',label:'Conteúdo',icon:'✎'},{id:'products',label:'Produtos',icon:'◇'},{id:'media',label:'Imagens',icon:'▧'},{id:'forms',label:'Formulários',icon:'◎'},{id:'audit',label:'Atividade',icon:'↻'}];

export function AdminDashboard() {
  const router = useRouter(); const [cms,setCms] = useState<(CmsDocument & { isSupabaseConfigured?: boolean }) | null>(null); const [tab,setTab] = useState<Tab>('overview'); const [query,setQuery] = useState(''); const [editing,setEditing] = useState<ContentEntry | null>(null); const [editingProduct,setEditingProduct] = useState<Product | null>(null); const [creatingProduct,setCreatingProduct] = useState(false); const [editingMedia,setEditingMedia] = useState<MediaItem | null>(null); const [creating,setCreating] = useState(false); const [notice,setNotice] = useState(''); const [busy,setBusy] = useState(false); const [mobileNav,setMobileNav] = useState(false);
  const load = useCallback(async()=>{ const response=await fetch('/api/admin/cms',{cache:'no-store'}); if(response.status===401){router.refresh();return;} setCms(await response.json()); },[router]);
  useEffect(()=>{load()},[load]);
  const filtered = useMemo(()=>cms?.content.filter(item => `${item.label} ${item.group} ${item.key}`.toLowerCase().includes(query.toLowerCase())) ?? [],[cms,query]);
  async function mutate(method:string,body:unknown){setBusy(true);const response=await fetch('/api/admin/cms',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const payload=await response.json();setBusy(false);if(!response.ok){setNotice(payload.error??'Não foi possível salvar.');return false;}await load();setNotice('Alterações salvas com sucesso.');setTimeout(()=>setNotice(''),2600);return true;}
  async function logout(){await fetch('/api/admin/auth/logout',{method:'POST'});router.refresh()}
  async function saveContent(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const body={resource:'content',id:editing?.id,key:data.get('key'),label:data.get('label'),group:data.get('group'),type:data.get('type'),value:data.get('value'),status:data.get('status')};if(await mutate(editing?'PATCH':'POST',body)){setEditing(null);setCreating(false)}}
  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const response=await fetch('/api/admin/media',{method:'POST',body:new FormData(event.currentTarget)});const payload=await response.json();setBusy(false);if(!response.ok)return setNotice(payload.error);(event.currentTarget as HTMLFormElement).reset();setNotice('Imagem enviada com sucesso.');await load()}
  async function saveMedia(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editingMedia)return;const data=new FormData(event.currentTarget);if(await mutate('PATCH',{resource:'media',id:editingMedia.id,name:data.get('name'),alt:data.get('alt')}))setEditingMedia(null)}
  async function saveProduct(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const specifications=String(data.get('specifications')||'').split('\n').filter(Boolean).map(line=>{const [label,...value]=line.split('|');return{label:label.trim(),value:value.join('|').trim()}});const tiers=String(data.get('tiers')||'').split('\n').filter(Boolean).map(line=>{const [min,price]=line.split('|');return{min:Number(min),price:Number(String(price).replace(',','.'))}});const body={resource:'product',id:editingProduct?.id,name:data.get('name'),shortName:data.get('shortName'),slug:data.get('slug'),sku:data.get('sku'),category:data.get('category'),description:data.get('description'),image:data.get('image'),minOrder:Number(data.get('minOrder')),unit:data.get('unit'),stock:Number(data.get('stock')),featured:data.get('featured')==='on',tags:String(data.get('tags')||'').split(',').map(tag=>tag.trim()).filter(Boolean),specifications,tiers};if(await mutate(editingProduct?'PATCH':'POST',body)){setEditingProduct(null);setCreatingProduct(false)}}
  if(!cms) return <div className="cms-loading"><span>✦</span><p>Preparando seu universo…</p></div>;
  const newForms=cms.submissions.filter(item=>item.status==='new').length;
  return <div className="cms-shell">
    <aside className={`cms-sidebar ${mobileNav?'is-open':''}`}><div className="cms-brand"><img src="/logo_mundo_encantado.svg" alt="Mundo Encantado"/><span>PAINEL CMS</span></div><nav>{nav.map(item=><button key={item.id} className={tab===item.id?'active':''} onClick={()=>{setTab(item.id);setMobileNav(false)}}><i>{item.icon}</i>{item.label}{item.id==='forms'&&newForms>0&&<b>{newForms}</b>}</button>)}</nav><a className="cms-view-site" href="/mundo-encantado" target="_blank">Ver site publicado ↗</a><div className="cms-profile"><span>ME</span><div><strong>Administrador</strong><small>Acesso total</small></div><button onClick={logout} title="Sair">↪</button></div></aside>
    <main className="cms-main"><header className="cms-topbar"><button className="cms-menu" onClick={()=>setMobileNav(!mobileNav)}>☰</button><div><p>{new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}</p><h1>{tab==='overview'?'Bom dia.':nav.find(item=>item.id===tab)?.label}</h1></div><div className="cms-topbar__actions">{cms.isSupabaseConfigured === false && <span className="cms-status draft" style={{ marginRight: '1rem', backgroundColor: '#fff3cd', color: '#856404', border: '1px solid #ffeeba', textTransform: 'none', fontWeight: 'bold' }}>⚠️ Modo Demonstração (Local)</span>}<span className="cms-live"><i/> Site online</span>{tab==='content'&&<button className="cms-primary" onClick={()=>setCreating(true)}>＋ Novo conteúdo</button>}</div></header>
      {notice&&<div className={`cms-toast ${notice.includes('sucesso')?'ok':''}`} role="status">{notice}</div>}
      {tab==='overview'&&<><section className="cms-welcome"><div><p className="cms-kicker">CENTRAL DA MARCA</p><h2>Tudo certo no<br/><em>Mundo Encantado.</em></h2><p>Gerencie a experiência do site sem tocar em código.</p></div><Image src="/images/produtos-reais/kit-25x35-turma.png" alt="Kit Mundo Encantado" width={210} height={263}/><span className="cms-welcome__star">✦</span></section><section className="cms-metrics"><article><span>Conteúdos</span><strong>{cms.content.length}</strong><small>{cms.content.filter(i=>i.status==='published').length} publicados</small></article><article><span>Produtos</span><strong>{cms.products.length}</strong><small>Catálogo gerenciável</small></article><article><span>Imagens</span><strong>{cms.media.length}</strong><small>Biblioteca organizada</small></article><article><span>Novos contatos</span><strong>{newForms}</strong><small>{cms.submissions.length} no total</small></article></section><section className="cms-split"><article className="cms-panel"><div className="cms-panel__head"><div><p className="cms-kicker">ATALHOS</p><h3>O que deseja editar?</h3></div></div><div className="cms-shortcuts"><button onClick={()=>setTab('content')}><i>✎</i><span><b>Textos do site</b><small>Títulos, descrições e chamadas</small></span><em>→</em></button><button onClick={()=>setTab('products')}><i>◇</i><span><b>Catálogo de produtos</b><small>Itens, estoque e preços por volume</small></span><em>→</em></button><button onClick={()=>setTab('media')}><i>▧</i><span><b>Biblioteca de imagens</b><small>Envios e textos alternativos</small></span><em>→</em></button><button onClick={()=>setTab('forms')}><i>◎</i><span><b>Contatos recebidos</b><small>Leads e solicitações comerciais</small></span><em>→</em></button></div></article><article className="cms-panel cms-recent"><div className="cms-panel__head"><p className="cms-kicker">ATIVIDADE RECENTE</p><h3>Últimas alterações</h3></div>{cms.audit.slice(0,5).map(item=><div key={item.id}><i>✓</i><span><b>{item.action}</b><small>{item.resource}</small></span><time>{new Date(item.createdAt).toLocaleString('pt-BR')}</time></div>)}{!cms.audit.length&&<p className="cms-empty">As próximas alterações aparecerão aqui.</p>}</article></section></>}
      {tab==='content'&&<section className="cms-panel cms-content"><div className="cms-panel__head cms-toolbar"><div><p className="cms-kicker">CONTEÚDO DO SITE</p><h2>Textos e seções</h2></div><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar conteúdo…"/></label></div><div className="cms-content-list">{filtered.map(item=><article key={item.id}><div><span className="cms-group">{item.group}</span><h3>{item.label}</h3><code>{item.key}</code></div><p>{item.value}</p><span className={`cms-status ${item.status}`}>{item.status==='published'?'Publicado':'Rascunho'}</span><div className="cms-row-actions"><button onClick={()=>setEditing(item)}>Editar</button><button className="danger" onClick={()=>confirm('Excluir este conteúdo?')&&mutate('DELETE',{resource:'content',id:item.id})}>Excluir</button></div></article>)}</div></section>}
      {tab==='products'&&<section className="cms-panel cms-products"><div className="cms-panel__head"><div><p className="cms-kicker">CATÁLOGO COMERCIAL</p><h2>Produtos publicados</h2><p>Gerencie informações, imagens, estoque e faixas de preço exibidas no site.</p></div><button className="cms-primary" onClick={()=>setCreatingProduct(true)}>＋ Novo produto</button></div><div className="cms-products-list">{cms.products.map(product=><article key={product.id}><div className="cms-product-image"><Image src={product.image} alt={product.name} fill sizes="96px"/></div><div className="cms-product-copy"><span className="cms-group">{product.category}</span><h3>{product.name}</h3><code>{product.sku} · /{product.slug}</code></div><div className="cms-product-numbers"><span><b>{product.stock.toLocaleString('pt-BR')}</b> em estoque</span><span><b>{product.minOrder}</b> pedido mínimo</span></div><span className={`cms-status ${product.featured?'published':'draft'}`}>{product.featured?'Destaque':'Catálogo'}</span><div className="cms-row-actions"><button onClick={()=>setEditingProduct(product)}>Editar</button><button className="danger" onClick={()=>confirm('Excluir este produto do catálogo?')&&mutate('DELETE',{resource:'product',id:product.id})}>Excluir</button></div></article>)}</div></section>}
      {tab==='media'&&<><section className="cms-panel cms-upload"><div><p className="cms-kicker">BIBLIOTECA DE MÍDIA</p><h2>Imagens do site</h2><p>Use arquivos PNG, JPG, WebP ou AVIF de até 8 MB. As imagens são exibidas inteiras, sem cortes.</p></div><form onSubmit={upload}><input name="file" type="file" accept="image/png,image/jpeg,image/webp,image/avif" required/><input name="name" placeholder="Nome da imagem" required/><input name="alt" placeholder="Descrição acessível da imagem" required/><button className="cms-primary" disabled={busy}>{busy?'Enviando…':'Enviar imagem'}</button></form></section><section className="cms-media-grid">{cms.media.map(item=><MediaCard key={item.id} item={item} onEdit={()=>setEditingMedia(item)} onDelete={()=>mutate('DELETE',{resource:'media',id:item.id})}/>)}</section></>}
      {tab==='forms'&&<section className="cms-panel cms-forms"><div className="cms-panel__head"><div><p className="cms-kicker">CAIXA DE ENTRADA</p><h2>Formulários recebidos</h2></div></div>{cms.submissions.length?cms.submissions.map(item=><article key={item.id}><div><span className={`cms-status ${item.status}`}>{item.status==='new'?'Novo':item.status==='contacted'?'Contatado':'Arquivado'}</span><h3>{item.form}</h3><time>{new Date(item.createdAt).toLocaleString('pt-BR')}</time></div><dl>{Object.entries(item.data).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><div className="cms-row-actions"><button onClick={()=>mutate('PATCH',{resource:'submission',id:item.id,status:'contacted'})}>Marcar contatado</button><button onClick={()=>mutate('PATCH',{resource:'submission',id:item.id,status:'archived'})}>Arquivar</button><button className="danger" onClick={()=>confirm('Excluir contato?')&&mutate('DELETE',{resource:'submission',id:item.id})}>Excluir</button></div></article>):<div className="cms-empty-state"><span>◎</span><h3>Nenhum contato ainda</h3><p>As mensagens enviadas pelo site aparecerão aqui.</p></div>}</section>}
      {tab==='audit'&&<section className="cms-panel cms-audit"><div className="cms-panel__head"><div><p className="cms-kicker">SEGURANÇA E HISTÓRICO</p><h2>Atividade do CMS</h2></div></div>{cms.audit.map(item=><article key={item.id}><i>✓</i><div><strong>{item.action}</strong><span>{item.resource}</span></div><time>{new Date(item.createdAt).toLocaleString('pt-BR')}</time></article>)}</section>}
    </main>
    {(editing||creating)&&<div className="cms-modal-backdrop" onMouseDown={()=>{setEditing(null);setCreating(false)}}><div className="cms-modal" onMouseDown={e=>e.stopPropagation()}><button className="cms-modal__close" onClick={()=>{setEditing(null);setCreating(false)}}>×</button><p className="cms-kicker">{editing?'EDITAR CONTEÚDO':'NOVO CONTEÚDO'}</p><h2>{editing?.label??'Criar campo'}</h2><form onSubmit={saveContent}><div className="cms-form-row"><label>Seção<input name="group" defaultValue={editing?.group} required/></label><label>Nome do campo<input name="label" defaultValue={editing?.label} required/></label></div>{!editing&&<label>Chave única<input name="key" placeholder="secao.campo" pattern="[a-z0-9.-]+" required/></label>}<div className="cms-form-row"><label>Tipo<select name="type" defaultValue={editing?.type??'text'}>{(['text','textarea','image','url'] as ContentType[]).map(type=><option key={type}>{type}</option>)}</select></label><label>Status<select name="status" defaultValue={editing?.status??'draft'}><option value="published">Publicado</option><option value="draft">Rascunho</option></select></label></div><label>Conteúdo{editing?.type==='image'?<select name="value" defaultValue={editing.value}>{cms.media.map(image=><option value={image.url} key={image.id}>{image.name}</option>)}</select>:<textarea name="value" defaultValue={editing?.value} rows={6} required/>}</label><div className="cms-modal__actions"><button type="button" onClick={()=>{setEditing(null);setCreating(false)}}>Cancelar</button><button className="cms-primary" disabled={busy}>{busy?'Salvando…':'Salvar alterações'}</button></div></form></div></div>}
    {(editingProduct||creatingProduct)&&<div className="cms-modal-backdrop" onMouseDown={()=>{setEditingProduct(null);setCreatingProduct(false)}}><div className="cms-modal cms-product-modal" onMouseDown={e=>e.stopPropagation()}><button className="cms-modal__close" onClick={()=>{setEditingProduct(null);setCreatingProduct(false)}}>×</button><p className="cms-kicker">{editingProduct?'EDITAR PRODUTO':'NOVO PRODUTO'}</p><h2>{editingProduct?.name??'Adicionar ao catálogo'}</h2><form onSubmit={saveProduct}><div className="cms-form-row"><label>Nome completo<input name="name" defaultValue={editingProduct?.name} required/></label><label>Nome curto<input name="shortName" defaultValue={editingProduct?.shortName} required/></label></div><div className="cms-form-row"><label>Endereço (slug)<input name="slug" defaultValue={editingProduct?.slug} pattern="[a-z0-9-]+" required/></label><label>SKU<input name="sku" defaultValue={editingProduct?.sku} required/></label></div><label>Categoria<input name="category" defaultValue={editingProduct?.category} required/></label><label>Descrição<textarea name="description" defaultValue={editingProduct?.description} rows={4} required/></label><label>Imagem<select name="image" defaultValue={editingProduct?.image} required><option value="">Selecione uma imagem</option>{cms.media.map(image=><option value={image.url} key={image.id}>{image.name}</option>)}</select></label><div className="cms-form-row cms-form-row--three"><label>Pedido mínimo<input name="minOrder" type="number" min="1" defaultValue={editingProduct?.minOrder??1} required/></label><label>Unidade<input name="unit" defaultValue={editingProduct?.unit??'unidades'} required/></label><label>Estoque<input name="stock" type="number" min="0" defaultValue={editingProduct?.stock??0} required/></label></div><label>Etiquetas <small>(separadas por vírgula)</small><input name="tags" defaultValue={editingProduct?.tags.join(', ')} /></label><div className="cms-form-row"><label>Especificações <small>(uma por linha: Nome | Valor)</small><textarea name="specifications" rows={5} defaultValue={editingProduct?.specifications.map(item=>`${item.label} | ${item.value}`).join('\n')} required/></label><label>Preços por volume <small>(uma por linha: Quantidade | Preço)</small><textarea name="tiers" rows={5} defaultValue={editingProduct?.tiers.map(item=>`${item.min} | ${item.price.toFixed(2).replace('.',',')}`).join('\n')} required/></label></div><label className="cms-check"><input name="featured" type="checkbox" defaultChecked={editingProduct?.featured}/><span>Exibir como produto em destaque</span></label><div className="cms-modal__actions"><button type="button" onClick={()=>{setEditingProduct(null);setCreatingProduct(false)}}>Cancelar</button><button className="cms-primary" disabled={busy}>{busy?'Salvando…':'Salvar produto'}</button></div></form></div></div>}
    {editingMedia&&<div className="cms-modal-backdrop" onMouseDown={()=>setEditingMedia(null)}><div className="cms-modal cms-media-modal" onMouseDown={e=>e.stopPropagation()}><button className="cms-modal__close" onClick={()=>setEditingMedia(null)}>×</button><p className="cms-kicker">EDITAR IMAGEM</p><h2>Dados da mídia</h2><div className="cms-media-preview"><Image src={editingMedia.url} alt={editingMedia.alt} fill sizes="420px"/></div><form onSubmit={saveMedia}><label>Nome<input name="name" defaultValue={editingMedia.name} required/></label><label>Descrição acessível<textarea name="alt" defaultValue={editingMedia.alt} rows={3} required/></label><div className="cms-modal__actions"><button type="button" onClick={()=>setEditingMedia(null)}>Cancelar</button><button className="cms-primary" disabled={busy}>{busy?'Salvando…':'Salvar imagem'}</button></div></form></div></div>}
  </div>;
}

function MediaCard({item,onEdit,onDelete}:{item:MediaItem;onEdit:()=>void;onDelete:()=>void}) { return <article className="cms-media-card"><div><Image src={item.url} alt={item.alt} fill sizes="(max-width:700px) 50vw, 20vw"/></div><h3>{item.name}</h3><p>{item.alt}</p><footer><code>{item.width&&item.height?`${item.width} × ${item.height}`:'Imagem enviada'}</code><span><button className="edit" onClick={onEdit}>Editar</button><button onClick={()=>confirm('Remover esta imagem?')&&onDelete()}>Excluir</button></span></footer></article> }
